//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MevaPro.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Projeler
    {
        public int ProjeId { get; set; }
        public string Baslik { get; set; }
        [UIHint("tinymce_full_compressed"), AllowHtml]
        [Display(Name = "Proje Detayý")]
        public string Icerik { get; set; }
        public string Foto { get; set; }
        public string seourl { get; set; }
    }
}
